"""
AI Analyzer — Claude API Integration
Sends scan results to Claude AI for intelligent threat analysis and report generation.
"""

import json
import os
import datetime
import anthropic

LOG_FILE = "activity_log.json"
AI_REPORT_FILE = "ai_threat_report.md"

def load_log():
    if not os.path.exists(LOG_FILE):
        print("No scan data found. Please run monitor.py first.")
        return None
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def analyze_with_claude(log_data):
    """Sends scan data to Claude AI for intelligent threat analysis."""
    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))

    scans = log_data["scans"]
    all_alerts = log_data["alerts"]

    # Build a clean summary to send to Claude
    scan_summary = {
        "total_scans": len(scans),
        "total_alerts": len(all_alerts),
        "alerts_by_severity": {
            "HIGH": sum(1 for a in all_alerts if a['severity'] == 'HIGH'),
            "MEDIUM": sum(1 for a in all_alerts if a['severity'] == 'MEDIUM'),
            "LOW": sum(1 for a in all_alerts if a['severity'] == 'LOW'),
        },
        "unique_alert_types": list({a['type'] for a in all_alerts}),
        "alerts": all_alerts[-20:],  # Send last 20 alerts to stay within limits
        "latest_scan": scans[-1] if scans else {}
    }

    prompt = f"""You are a senior cybersecurity analyst reviewing endpoint monitoring data.
    
Here is the scan data from an Endpoint Activity Monitor tool:

{json.dumps(scan_summary, indent=2)}

Please provide a professional security analysis report that includes:

1. **Threat Assessment** — Overall risk level (Critical/High/Medium/Low) and why
2. **Key Findings** — Most important threats detected and what they indicate
3. **Attack Pattern Analysis** — Do any alerts suggest a coordinated attack or specific threat actor behavior?
4. **Prioritized Recommendations** — Top 5 specific, actionable steps the system owner should take immediately
5. **False Positive Assessment** — Which alerts are likely false positives and why
6. **Monitoring Improvements** — What additional monitoring would strengthen detection

Write this as a formal incident response report a security engineer would present to management.
Be specific, technical, and actionable."""

    print("\nSending scan data to Claude AI for analysis...")
    print("This may take a few seconds...\n")

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1500,
        messages=[{"role": "user", "content": prompt}]
    )

    return message.content[0].text

def save_ai_report(analysis):
    """Saves the AI-generated report to a markdown file."""
    timestamp = datetime.datetime.now().strftime("%B %d, %Y at %H:%M:%S")
    
    report = f"""# AI THREAT ANALYSIS REPORT
**Generated by Claude AI:** {timestamp}  
**Tool:** Endpoint Activity Monitor — Hiyab Hailu  

---

{analysis}

---
*This report was generated using Claude AI (Anthropic) to provide intelligent threat analysis of endpoint monitoring data.*
"""
    with open(AI_REPORT_FILE, "w") as f:
        f.write(report)

    print(f"✔ AI report saved to {AI_REPORT_FILE}")
    return report

def main():
    print("=" * 55)
    print("   AI THREAT ANALYZER — Powered by Claude")
    print("   Endpoint Activity Monitor | Hiyab Hailu")
    print("=" * 55)

    # Check for API key
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("\n⚠ ANTHROPIC_API_KEY not set.")
        print("Set it with: export ANTHROPIC_API_KEY=your_key_here")
        return

    log_data = load_log()
    if not log_data:
        return

    print(f"\nLoaded {len(log_data['scans'])} scans and {len(log_data['alerts'])} alerts.")

    analysis = analyze_with_claude(log_data)

    print("\n" + "=" * 55)
    print("AI ANALYSIS COMPLETE")
    print("=" * 55)
    print(analysis)

    save_ai_report(analysis)

    print("\nDone! Check:")
    print(f"  → {AI_REPORT_FILE} (AI-generated threat report)")

if __name__ == "__main__":
    main()
